<!DOCTYPE html>
<html>

<head>
    <title>{{ $title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <style>
        @media print {
            .no-print {
                display: none !important;
            }

            .table {
                font-size: 12px;
            }

            .badge {
                padding: 3px 8px;
                font-size: 10px;
            }
        }

        .print-header {
            border-bottom: 2px solid #333;
            margin-bottom: 20px;
            padding-bottom: 10px;
        }

        .print-title {
            font-size: 24px;
            font-weight: bold;
            color: #333;
        }

        .print-subtitle {
            font-size: 14px;
            color: #666;
        }

        .table th {
            background-color: #f8f9fa !important;
            font-weight: 600;
        }

        .filter-info {
            background: #f8f9fa;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 15px;
            font-size: 13px;
        }
    </style>
</head>

<body>
    <div class="container-fluid mt-3">
        <!-- Print Header -->
        <div class="print-header">
            <div class="row">
                <div class="col-8">
                    <div class="print-title">Booking Sessions Report</div>
                    <div class="print-subtitle">
                        Generated on: {{ date('F j, Y, g:i a') }}
                    </div>
                </div>
                <div class="col-4 text-end">
                    <button class="btn btn-primary btn-sm no-print" onclick="window.print()">
                        <i class="fas fa-print"></i> Print
                    </button>
                    <button class="btn btn-secondary btn-sm no-print" onclick="window.close()">
                        <i class="fas fa-times"></i> Close
                    </button>
                </div>
            </div>
        </div>

        <!-- Filter Information -->
        @if (!empty(array_filter($filters)))
            <div class="filter-info">
                <strong>Filters Applied:</strong>
                @if (isset($filters['month']) && $filters['month'])
                    <span class="badge bg-info me-2">Month: {{ $filters['month'] }}</span>
                @endif
                @if (isset($filters['year']) && $filters['year'])
                    <span class="badge bg-info me-2">Year: {{ $filters['year'] }}</span>
                @endif
                @if (isset($filters['language']) && $filters['language'])
                    <span class="badge bg-info me-2">Language: {{ $filters['language'] }}</span>
                @endif
                @if (isset($filters['slot']) && $filters['slot'])
                    <span class="badge bg-info me-2">Slot: {{ $filters['slot'] }}</span>
                @endif
            </div>
        @endif



        <!-- Bookings Table -->
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Student Name</th>
                        <th>Student Email</th>
                        <th>Month</th>
                        <th>Year</th>
                        <th>Slot Time</th>
                        <th>Language</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($bookings as $index => $booking)
                        <tr>
                            <td>{{ $index + 1 }}</td>
                            <td>{{ $booking->student->name ?? 'N/A' }}</td>
                            <td>{{ $booking->student->email ?? 'N/A' }}</td>
                            <td>{{ $booking->month }}</td>
                            <td>{{ $booking->year }}</td>
                            <td>{{ $booking->slot }}</td>
                            <td>{{ $booking->language }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <!-- Print Footer -->
        <div class="row mt-4">
            <div class="col-12 text-center">
                <div class="text-muted small">
                    Generated by Booking Management System
                </div>
            </div>
        </div>
    </div>



    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    <script>
        function exportToPDF() {
            window.location.href = window.location.pathname + '?export=pdf' + window.location.search;
        }

        // Auto print option
        @if (request('auto_print'))
            window.onload = function() {
                window.print();
            }
        @endif
    </script>
</body>

</html>
